# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-22 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
