# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-22 10:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190422_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='parent_contact',
            field=models.PositiveIntegerField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')]),
        ),
    ]
