# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-22 10:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190422_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='parent_contact',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
