# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-04-23 12:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190422_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecvData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('contact_det', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('loc_long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('loc_lat', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='kid',
            name='id',
        ),
        migrations.AlterField(
            model_name='kid',
            name='parent_contact',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
