# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-22 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190423_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='recvdata',
            name='img',
            field=models.ImageField(default='Image/None/No-img.jpg', upload_to='Image/clientUpload'),
        ),
        migrations.AlterField(
            model_name='recvdata',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recvdata',
            name='loc_lat',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
        migrations.AlterField(
            model_name='recvdata',
            name='loc_long',
            field=models.DecimalField(decimal_places=9, max_digits=12),
        ),
    ]
