# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-28 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190522_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid',
            name='image',
            field=models.ImageField(default='Image/None/No-img.jpg', upload_to='Image/Saved'),
        ),
    ]
